sudo: required
services:
  - docker

before_install:
  - docker build -t codey/docker-react -f Dockerfile.dev .

script:
  - docker run codey/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_ACCESS_SECRET
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-203301068892"
  bucket_path: "docker-react"
  on:
    branch: master